name: flutter_responsive_kit
description: A lightweight and flexible Flutter package for building fully responsive UIs — mobile, tablet, and desktop — with ease.
version: 0.0.3+1

homepage: https://github.com/Amar5499/flutter_responsive_kit
repository: https://github.com/Amar5499/flutter_responsive_kit
license: MIT

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/logo.png
